<?php /* @var $this Aoe_EeIndexerStats_Block_Adminhtml_IndexerStats */ ?>

<div class="content-header">
    <table cellspacing="0">
        <tbody>
        <tr>
            <td style="width:50%;"><h3 class="icon-head head-adminhtml-process"><?php echo $this->__('EE Indexer Stats'); ?></h3></td>
            <td class="form-buttons"></td>
        </tr>
        </tbody>
    </table>
</div>

<?php /*
<?php if ($this->isLocked()): ?>Locked<?php else: ?>Not Locked<?php endif; ?>
 */ ?>

<div class="grid">
    <table class="data" cellspacing="0">
        <thead>
        <tr class="headings">
            <th class=" no-link"><span class="nobr"><?php echo $this->__('Changelog Name'); ?></span></th>
            <th class=" no-link"><span class="nobr"><?php echo $this->__('Index Option'); ?></span></th>
            <th class=" no-link"><span class="nobr"><?php echo $this->__('Table'); ?></span></th>
            <th class=" no-link"><span class="nobr"><?php echo $this->__('Models'); ?></span></th>
            <th class=" no-link"><span class="nobr"><?php echo $this->__('Current version id'); ?></span></th>
            <th class=" no-link"><span class="nobr"><?php echo $this->__('Last version id'); ?></span></th>
            <th class=" no-link"><span class="nobr"><?php echo $this->__('Processed'); ?></span></th>
            <th class=" no-link"><span class="nobr"><?php echo $this->__('Unprocessed'); ?></span></th>
            <th class=" no-link"><span class="nobr"><?php echo $this->__('Status'); ?></span></th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($this->getIndexerStats() as $indexerStat): ?>
            <tr>
                <td class="a-left"><?php echo $indexerStat['changelog_name'] ?></td>
                <td class="a-left"><?php echo $this->getIndexOption($indexerStat['tablename']) ?></td>
                <td class="a-left"><?php echo $indexerStat['tablename'] ?></td>
                <td class="a-left">
                    <strong><?php echo $this->__('Model'); ?>:</strong> <?php echo $indexerStat['model'] ?><br />
                    <strong><?php echo $this->__('Changelog'); ?>:</strong> <?php echo $indexerStat['action_model_changelog'] ?><br />
                    <strong><?php echo $this->__('All'); ?>:</strong> <?php echo $indexerStat['action_model_all'] ?>
                </td>
                <td class="a-left"><?php echo $indexerStat['current_version_id'] ?></td>
                <td class="a-left"><?php echo $indexerStat['last_version_id'] ?></td>
                <td class="a-left"><?php echo $indexerStat['count_processed'] ?></td>
                <td class="a-left"><?php echo $indexerStat['count_unprocessed'] ?></td>
                <td class="a-left"><?php echo $this->renderStatus($indexerStat['status']); ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>
